create table role (id integer generated by default as identity, name varchar(255), primary key (id));
create table tb_user (id integer generated by default as identity, password varchar(255), username varchar(255), primary key (id));
create table tb_user_role_list (role_list_id integer not null unique, user_id integer not null);
alter table if exists tb_user_role_list add constraint FKk9j4uf5h926hjdwiunau41d4b foreign key (role_list_id) references role;
alter table if exists tb_user_role_list add constraint FK912baa732c4n3tdyjuibx2elh foreign key (user_id) references tb_user;
